# xinitrc file for testing our window manager.
xrdb -load Xresources

#compton --config="./compton.conf" &
# 0. Set wallpaper using feh
#feh --bg-scale ./wallpaper.jpg &

# 1. Start some programs to play with.
#xterm &
#xclock &
#albert &
#xeyes &
#pcmanfm &
#alacritty &
#firefox &
#mousepad &

# polybar
polybar --config="./polyconf" example 2>polylog &

# 2. Start our window manager.


#exec $(RUST_LOG=hadlock ../target/debug/hadlock /home/ada/Programming/rust/hobby/hadlock/config/hadlock.ron)
exec $(RUST_LOG=hadlock ../target/debug/hadlock /home/ada/.config/hadlock/hadlock.ron)
