name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxinerama-dev
          sudo apt install libdbus-1-dev
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@master
      with:
        name: Hadlock
        path: target/release/hadlock
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/hadlock
        asset_name: Hadlock
        tag: ${{ github.ref }}
        overwrite: true
