name: Rust

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxinerama-dev
          sudo apt install libdbus-1-dev
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@master
      with:
        name: Hadlock
        path: target/release/hadlock
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
            Changes in this release
        draft: false
        prerelease: false


