name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxinerama-dev
          sudo apt install libdbus-1-dev
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@master
      with:
        name: Hadlock
        path: target/release/hadlock

on:
  push:
    branches:
        - master
    tags:
      - 'release'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
